sudo: required

language: generic

env:
    - TEST_SUITE=test
    - TEST_SUITE=itest

services:
    - docker

before_install:
    - sudo apt-get install luarocks lua5.1
    - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
    - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
    - sudo apt-get update && sudo apt-get install -y openresty openresty-opm openresty-resty

before_script:
    - make cook-image

script:
    - make $TEST_SUITE
