[workspace]
members = ["casper-server"]

[profile.release]
opt-level = 3
debug = true
codegen-units = 1

[profile.dev]
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
split-debuginfo = "unpacked"

[profile.bench]
debug = true
