[package]
name = "casper-runtime"
version = "0.1.0"
edition = "2018"

[dependencies]
mlua = { version = "0.7", features = ["luajit52", "async", "send", "vendored", "serialize"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1"

# url = "2.0"
http = "0.2"
form_urlencoded = "1"
serde_json = "1"
serde_yaml = "0.8"
bytes = "1"
toml = "0.5"
serde = { version = "1", features = ["derive"] }
hyper_serde = { git = "https://github.com/servo/hyper_serde" }
flexbuffers = "2"
bstr = "0.2.17"

once_cell = "1"
pretty_env_logger = "0.4"
anyhow = "1"
num_cpus = "1.13"
regex = "1.5"
linked-hash-map = "0.5.4"

# dynamodb requirements
hex = "0.4.3"
aws-config = "0.2.0"
aws-sdk-dynamodb = "0.2.0"
