[package]
name = "casper2"
version = "0.1.0"
edition = "2018"

[dependencies]
mlua = { version = "0.6.5", features = ["luajit", "async", "send", "vendored", "serialize"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
futures-util = "0.3"

# url = "2.0"
http = "0.2"
form_urlencoded = "1"
serde_json = "1"
bytes = "1"
toml = "0.5"
serde = { version = "1", features = ["derive"] }

once_cell = "1"
pretty_env_logger = "0.4"
anyhow = "1"
