[package]
edition = "2021"
name = "casper-server"
version = "0.1.0"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.21"
bitflags = "1.3.2"
blake3 = "1.0"
bytes = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive", "env"] }
core_affinity = "0.8.0"
csv = "1.0"
dyn-clone = "1"
flexbuffers = "2"
form_urlencoded = "1"
futures = "0.3"
futures-util = "0.3"
hex = "0.4.3"
linked-hash-map = "0.5.4"
mini-moka = "0.10"
moka = { version = "0.11", features = ["future"] }
ntex = { version = "0.6.5", features = ["tokio", "openssl"] }
num_cpus = "1.13"
num_threads = "0.1"
once_cell = "1"
openssl = "0.10"
opentelemetry = { version = "0.19", features = ["rt-tokio", "metrics"] }
opentelemetry-prometheus = "0.12"
ouroboros = "0.15"
parking_lot = "0.12"
percent-encoding = "2.2"
pin-project-lite = "0.2.8"
prometheus = "0.13"
rand = "0.8"
regex = "1.5"
ripemd = "0.1"
scopeguard = "1.1.0"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"
serde_qs = "0.12"
serde_yaml = "0.9"
sys-info = "0.9"
thiserror = "1"
time = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = "0.3"
zstd = "0.12"

[dev-dependencies]
tokio-stream = { version = "0.1", features = ["time"] }

[dependencies.mlua]
features = ["luau", "async", "serialize", "macros", "unstable"]
version = "0.9.0-beta.3"

[dependencies.fred]
features = ["enable-native-tls"]
version = "6.3"

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = "0.5"
