name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install depdendencies
        run: |
          sudo apt-get install luarocks lua5.1
          sudo apt-get install libyaml-dev
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update && sudo apt-get install -y openresty openresty-opm openresty-resty
  
      - name: Run unit tests
        run: make test
    
      - name: Run integration tests
        run: make itest
